version: '3'
services:
  app:
    container_name: app
    image: node
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongo
      - rabbitmq
    environment:
      NODE_ENV: development
    ports:
      - 8001:8000
      - 9230:9229
    command: yarn debug 
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./data/db:/data/db
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15673:15672
      - 5673:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq